apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "debezium.fullname" . }}-config
  labels:
    {{- include "debezium.labels" . | nindent 4 }}

data:
  BOOTSTRAP_SERVERS: {{ .Values.env.BOOTSTRAP_SERVERS | quote }}

  GROUP_ID: {{ .Values.env.GROUP_ID | quote }}

  CONFIG_STORAGE_TOPIC: {{ .Values.env.CONFIG_STORAGE_TOPIC | quote }}
  OFFSET_STORAGE_TOPIC: {{ .Values.env.OFFSET_STORAGE_TOPIC | quote }}
  STATUS_STORAGE_TOPIC: {{ .Values.env.STATUS_STORAGE_TOPIC | quote }}

  CONFIG_STORAGE_REPLICATION_FACTOR: {{ .Values.env.CONFIG_STORAGE_REPLICATION_FACTOR | quote }}
  OFFSET_STORAGE_REPLICATION_FACTOR: {{ .Values.env.OFFSET_STORAGE_REPLICATION_FACTOR | quote }}
  STATUS_STORAGE_REPLICATION_FACTOR: {{ .Values.env.STATUS_STORAGE_REPLICATION_FACTOR | quote }}

  KEY_CONVERTER: {{ .Values.env.KEY_CONVERTER | quote }}
  VALUE_CONVERTER: {{ .Values.env.VALUE_CONVERTER | quote }}

  KEY_CONVERTER_SCHEMAS_ENABLE: {{ .Values.env.KEY_CONVERTER_SCHEMAS_ENABLE | quote }}
  VALUE_CONVERTER_SCHEMAS_ENABLE: {{ .Values.env.VALUE_CONVERTER_SCHEMAS_ENABLE | quote }}

  REST_ADVERTISED_HOST_NAME: {{ .Values.env.REST_ADVERTISED_HOST_NAME | quote }}
  REST_PORT: {{ .Values.env.REST_PORT | quote }}

  PLUGIN_PATH: {{ .Values.env.PLUGIN_PATH | quote }}

  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}