apiVersion: v1
kind: Secret

metadata:
  name: {{ include "debezium.fullname" . }}-secret
  labels:
    {{- include "debezium.labels" . | nindent 4 }}

type: Opaque

stringData:
  DATABASE_USER: {{ index .Values.connector.config "database.user" | quote }}
  DATABASE_PASSWORD: {{ index .Values.connector.config "database.password" | quote }}