apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: cdc-todo-app
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
          slack_api_url: 'https://hooks.slack.com/services/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'
        route:
          group_by: ['alertname', 'namespace']
          group_wait: 10s
          group_interval: 30s
          repeat_interval: 1h
          receiver: 'slack-notifications'
          routes:
            - receiver: 'slack-notifications'
              continue: true
        receivers:
          - name: 'slack-notifications'
            slack_configs:
              - channel: '#new-channel'
                send_resolved: true
                title: '🚨 [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}'
                text: >-
                  *Alert:* {{ .CommonAnnotations.summary }}
                  *Details:* {{ .CommonAnnotations.description }}
                  *Severity:* `{{ .CommonLabels.severity }}`
                  *Namespace:* `{{ .CommonLabels.namespace }}`

    prometheus:
      prometheusSpec:
        scrapeInterval: "15s"
        evaluationInterval: "15s"
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-kafka-exporter
  namespace: cdc-todo-app
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-kafka-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kafkaServer:
      - kafka.cdc-todo-app.svc.cluster.local:9092
