replicaCount: 1

image:
  repository: 2024dock/cdc-backend
  pullPolicy: IfNotPresent
  tag: "v1.0.8-amd64"

service:
  type: ClusterIP
  port: 8080
serviceAccount:
  create: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

ingress:
  enabled: false
