replicaCount: 1

image:
  repository: 2024dock/cdc-frontend
  pullPolicy: IfNotPresent
  tag: "v1.0.8-amd64"

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false

ingress:
  enabled: false