apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "kafka.fullname" . }}-config

data:
  KAFKA_CFG_NODE_ID: {{ .Values.config.KAFKA_CFG_NODE_ID | quote }}
  KAFKA_CFG_PROCESS_ROLES: {{ .Values.config.KAFKA_CFG_PROCESS_ROLES | quote }}
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: {{ .Values.config.KAFKA_CFG_CONTROLLER_LISTENER_NAMES | quote }}
  KAFKA_CFG_LISTENERS: {{ .Values.config.KAFKA_CFG_LISTENERS | quote }}
  KAFKA_CFG_ADVERTISED_LISTENERS: {{ .Values.config.KAFKA_CFG_ADVERTISED_LISTENERS | quote }}
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: {{ .Values.config.KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP | quote }}
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: {{ .Values.config.KAFKA_CFG_CONTROLLER_QUORUM_VOTERS | quote }}
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: {{ .Values.config.KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE | quote }}
  KAFKA_CFG_NUM_PARTITIONS: {{ .Values.config.KAFKA_CFG_NUM_PARTITIONS | quote }}
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: {{ .Values.config.KAFKA_CFG_DEFAULT_REPLICATION_FACTOR | quote }}
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: {{ .Values.config.KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR | quote }}
  KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: {{ .Values.config.KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR | quote }}
  KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: {{ .Values.config.KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR | quote }}