{{- if or (not .Values.secret.JWT_SECRET) (lt (len .Values.secret.JWT_SECRET) 32) }}
{{- fail "auth-service.secret.JWT_SECRET must be set to at least 32 characters" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
