apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

data:
  POSTGRES_PORT: "5432"

  WAL_LEVEL: {{ .Values.postgresql.walLevel | quote }}
  MAX_CONNECTIONS: {{ .Values.postgresql.maxConnections | quote }}
  MAX_WAL_SENDERS: {{ .Values.postgresql.maxWalSenders | quote }}
  MAX_REPLICATION_SLOTS: {{ .Values.postgresql.maxReplicationSlots | quote }}