apiVersion: v2
name: raju-stack
version: 26.100.1
appVersion: v26.100.1
dependencies:
- name: backend
  repository: file://../backend
  version: 0.1.0
- name: frontend
  repository: file://../frontend
  version: 0.1.0
- name: consumer
  repository: file://../consumer
  version: 0.1.0
