backend:
  replicaCount: 1
  image:
    repository: 2024dock/cdc-backend
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
serviceAccount:
  create: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

ingress:
  enabled: false

frontend:
  replicaCount: 1
  image:
    repository: 2024dock/cdc-frontend
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
serviceAccount:
  create: false
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false

ingress:
  enabled: false

consumer:
  replicaCount: 1
  image:
    repository: 2024dock/cdc-consumer
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
serviceAccount:
  create: false
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false

ingress:
  enabled: false