containers:
  - name: frontend

    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}

    ports:
      - name: http
        containerPort: {{ .Values.service.targetPort }}

    envFrom:
      - configMapRef:
          name: {{ include "frontend.fullname" . }}-config

    resources:
      {{- toYaml .Values.resources | nindent 6 }}

    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 15
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5

    startupProbe:
      httpGet:
        path: /
        port: http
      periodSeconds: 10
      failureThreshold: 30