namespace: cdc-todo-app

images:
  postgres: postgres:15-alpine
  zookeeper: confluentinc/cp-zookeeper:7.6.0
  kafka: confluentinc/cp-kafka:7.6.0
  debezium: debezium/connect:2.5
  elasticsearch: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
  backend: 2024dock/cdc-backend:v1.0.3-amd64
  consumer: 2024dock/cdc-consumer:v1.0.0
  frontend: 2024dock/cdc-frontend:v1.0.3-amd64
  kowl: docker.redpanda.com/redpandadata/console:v2.5.2
  kibana: docker.elastic.co/kibana/kibana:8.13.1

persistence:
  storageClass: ""
  postgresSize: 2Gi
  kafkaSize: 2Gi
  elasticsearchSize: 2Gi

nodePorts:
  frontend: 30080
  kowl: 30081
  kibana: 30561