frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: 2024dock/cdc-frontend
    tag: "v1.0.22"
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: todo.local
        paths:
          - path: /
            pathType: Prefix
