containers:
  - name: consumer

    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}

    envFrom:
      - configMapRef:
          name: {{ include "consumer.fullname" . }}-config

    resources:
      {{- toYaml .Values.resources | nindent 6 }}

    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - ps aux | grep node
      initialDelaySeconds: 20
      periodSeconds: 10

    readinessProbe:
      exec:
        command:
          - sh
          - -c
          - ps aux | grep node
      initialDelaySeconds: 5
      periodSeconds: 5

    startupProbe:
      exec:
        command:
          - sh
          - -c
          - ps aux | grep node
      periodSeconds: 10
      failureThreshold: 30