apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "consumer.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "consumer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      serviceAccountName: {{ include "consumer.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}

      containers:
        - name: consumer

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "consumer.fullname" . }}-config

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep node
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep node
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep node
            periodSeconds: 10
            failureThreshold: 30

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}