apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cdc-platform
  namespace: cdc-todo-app
spec:
  interval: 1m
  chart:
    spec:
      chart: apps/base/cdc-platform
      sourceRef:
        kind: GitRepository
        name: flux-system      # <-- Yahan "devops-project" se badal kar "flux-system" karein
        namespace: flux-system
