apiVersion: helm.toolkit.fluxcd.io/v2beta1 # or v2
kind: HelmRelease
metadata:
  name: cdc-platform
  namespace: cdc-todo-app
spec:
  interval: 1m
  chart:
    spec:
      chart: apps/base/cdc-platform
      sourceRef:
        kind: GitRepository
        name: devops-project # your flux GitRepository name
        namespace: flux-system
      version: "v26.100.1" # <-- UPDATE THIS TO v26.100.1
